name: 'Create K3d Temporary Cluster'
description: '⎈ Github action to helm releases testings'
author: 'Janusz Kujawa <janusz.kujawa@gmail.com>'
runs:
  using: 'k3d'
  main: 'bin/k3d'
branding:
  icon: 'thumbs-up'
  color: 'gray-dark'
inputs:
  event:
    description: 'The event to perform on the pull request review.'
    default: 'APPROVE'
  body:
    description: 'The contents of the review body comment. Required when event is COMMENT or REQUEST_CHANGES.'
  cluster-size:
    description: 'The GH_TOKEN secret can be passed in using {{ secrets.GH_TOKEN }}'
    required: true
