name: 'Create K3d Temporary Cluster'
description: "⎈ Github action to spinup temp cluster"
author: 'Janusz Kujawa <janusz.kujawa@gmail.com>'
inputs:
  cluster_name:
    description: "Cluster name: "
    required: true
  cluster_version:
    description: "K3d version: "
    required: false
runs:
  using: composite
  steps:
    - name: "Create k3d cluster"
      id: main
      env:
        CLUSTER_NAME: ${{ inputs.name }}
        CONF: ${{ inputs.conf }}
        K3D_VERSION: ${{ inputs.version }}
      shell: bash
      run: ${{ github.action_path }}/bin/run.sh -c -c ${{ env.CLUSTER_NAME }}
    - name: Check if cluster ${{ env.CLUSTER_NAME}} is created
      id: verify
      shell: bash
      run: ${{ github.action_path }}/bin/run.sh -c ${{ env.CLUSTER_NAME }}
