name: 'Create K3d Temporary Cluster'
description: "⎈ Github action to helm releases testings"
author: 'Janusz Kujawa <janusz.kujawa@gmail.com>'
inputs:
  name:
    description: "Cluster name: "
    required: true
  args:
    description: "Extra args: "
    required: false
  size:
    description: "Size based on config file: "
  k3d-version:
    description: "K3d version: "
    required: false
runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: ${{ github.action_path }}/run.sh deploy
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        ARGS: ${{ inputs.args }}
        K3D_VERSION: ${{ inputs.k3d-version }}
