name: 'Create K3d Temporary Cluster'
description: "⎈ Github action to helm releases testings"
author: 'Janusz Kujawa <janusz.kujawa@gmail.com>'
inputs:
  name:
    description: "Cluster name: "
    required: true
  conf:
    description: "Size based on config file: "
    required: false
  version:
    description: "K3d version: "
    required: false
runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: ${{ github.action_path }}/bin/run.sh deploy
      env:
        CLUSTER_NAME: ${{ inputs.name }}
        CONF: ${{ inputs.conf }}
        K3D_VERSION: ${{ inputs.version }}
