name: 'Create K3d Temporary Cluster'
description: "⎈ Github action to spinup temp cluster"
author: 'Janusz Kujawa <janusz.kujawa@gmail.com>'
branding:
  icon: 'thumbs-up'
  color: 'gray-dark'
inputs:
  cluster_name:
    description: "Cluster name: "
    required: true
  cluster_version:
    description: "K3d version: "
    required: false
runs:
  using: composite
  env:
    CLUSTER_NAME: ${{ inputs.cluster_name }}
    K3D_VERSION: ${{ inputs.version }}
  steps:
    - uses: actions/checkout@v3
    - name: Create k3d cluster
      id: main
      shell: bash
      run: ${{ github.action_path }}/bin/run.sh -c ${{ env.CLUSTER_NAME }}
    - name: Check if cluster ${{ env.CLUSTER_NAME}} is created
      id: verify
      shell: bash
      run: ${{ github.action_path }}/bin/run.sh -l ${{ env.CLUSTER_NAME }}